language: php
php:
- '5.5'
- '5.4'
notifications:
  slack:
    rooms:
      secure: fpygL/ETTVc9GmAkzNw4lxS84Bes36G+AyGrybvHa3JrYDsn4iwoQisHR6SPdLdONoJnyW8RZIzvwh5DbVUHlp6aWcsWU+bCA2AnHVPs8td7th7kQpo46N/7ah7OuaOdYJ953HS2IXdC5lx3jelvauDJs3oXbPmgKTHsM4cT4TVceO65yj4W/vWuYMVQ9Knp8PmU5dA7EYTpLP8BmEprufDWfTh/BQwGtYMaQK2eEzCgW8wolqKaTUpItKACrx61woe6o+9ARzeT83x1bGL9leK44F3JH4mnihvXT2fLBBhsCWj8BLjIgMx97MS7/ohwWIvYkuZSMfIyxSNLRot1+eElPGML9/8x549b766Pn5EyfnoYYRZcKxrJQ5w9pyZU4+69mUiegli64suoH4jzjF16W/qqYiLswg1/pjVVL9Oj9zqfpF3WuDD1OiZzML+kL8BljlYMnjxOlf5VYsLk5QpzNMH+j7ncHkWMmfaEBZkxEZL3X+52+K2pu8EHCecy0ySnSA63J53rYhFtVOv83LP7UPSu1Ce67Nvb3eo8JmAj+TcsumMva+SYOI6jKFEz855bnRR3TOgODPwduXLVUjL4QQsTGySUvSEMtl1eXMLN6ITpAqBGHlB0gLIm40Eja9wbSOB9heJVPaKGLZhlm3ycHqUvtjDEsJ1HpVsBmO0=
